# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rl_server_pb2 as rl__server__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in rl_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RLServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextCommand = channel.unary_unary(
                '/RLServer/GetNextCommand',
                request_serializer=rl__server__pb2.GetNextCommandRequest.SerializeToString,
                response_deserializer=rl__server__pb2.Command.FromString,
                _registered_method=True)
        self.SendActionResponse = channel.unary_unary(
                '/RLServer/SendActionResponse',
                request_serializer=rl__server__pb2.SendActionResponseRequest.SerializeToString,
                response_deserializer=rl__server__pb2.ActionResponse.FromString,
                _registered_method=True)


class RLServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNextCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendActionResponse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RLServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextCommand,
                    request_deserializer=rl__server__pb2.GetNextCommandRequest.FromString,
                    response_serializer=rl__server__pb2.Command.SerializeToString,
            ),
            'SendActionResponse': grpc.unary_unary_rpc_method_handler(
                    servicer.SendActionResponse,
                    request_deserializer=rl__server__pb2.SendActionResponseRequest.FromString,
                    response_serializer=rl__server__pb2.ActionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RLServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RLServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RLServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNextCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RLServer/GetNextCommand',
            rl__server__pb2.GetNextCommandRequest.SerializeToString,
            rl__server__pb2.Command.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendActionResponse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RLServer/SendActionResponse',
            rl__server__pb2.SendActionResponseRequest.SerializeToString,
            rl__server__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
